export const theme_ghostie = {
  "--ck-font-family": "Quicksand",
  "--ck-border-radius": "24px",
  "--ck-connectbutton-font-size": "17px",
  "--ck-connectbutton-font-weight": "700",
  "--ck-connectbutton-border-radius": "14px",
  "--ck-connectbutton-color": "#000000",
  "--ck-connectbutton-background": "#ffffff",
  "--ck-connectbutton-box-shadow":
    "inset 0 0 0 2px #DFE4EC, 0 2px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-connectbutton-hover-background": "#F9FAFB",
  "--ck-connectbutton-balance-color": "#414451",
  "--ck-connectbutton-balance-background": "#F9FAFB",
  "--ck-connectbutton-balance-box-shadow":
    "0 2px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-connectbutton-balance-hover-background": "#F5F7F9",
  "--ck-connectbutton-balance-hover-box-shadow":
    "0 2px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-connectbutton-balance-active-box-shadow":
    "0 0 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-connectbutton-active-background": "#F5F7F9",
  "--ck-connectbutton-active-box-shadow":
    "inset 0 0 0 2px #CFD7E2, 0 0px 0 0 #CFD7E2, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-primary-button-border-radius": "18px",
  "--ck-primary-button-color": "#151C3B",
  "--ck-primary-button-background": "#ffffff",
  "--ck-primary-button-box-shadow":
    "inset 0 0 0 2px #DFE4EC, inset  0 -4px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-primary-button-hover-background": "#DEE1ED",
  "--ck-primary-button-hover-box-shadow":
    "inset 0 0 0 2px #DFE4EC, inset  0 -2px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-secondary-button-border-radius": "16px",
  "--ck-secondary-button-color": "#151C3B",
  "--ck-secondary-button-background": "#ffffff",
  "--ck-secondary-button-box-shadow":
    "inset 0 0 0 2px #DFE4EC, inset  0 -4px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-secondary-button-hover-background": "#DEE1ED",
  "--ck-secondary-button-hover-box-shadow":
    "inset 0 0 0 2px #DFE4EC, inset  0 -2px 0 0 #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-focus-color": "#1A88F8",
  "--ck-modal-box-shadow": "0px 3px 16px rgba(0, 0, 0, 0.08)",
  "--ck-body-color": "#151C3B",
  "--ck-body-color-muted": "#757A8E",
  "--ck-body-color-muted-hover": "#000000",
  "--ck-body-background": "#F4F4F8",
  "--ck-body-background-transparent": "rgba(255,255,255,0)",
  "--ck-body-background-secondary": "#E9E9F1",
  "--ck-body-background-secondary-hover-background": "#e0e4eb",
  "--ck-body-background-secondary-hover-outline": "#4282FF",
  "--ck-body-background-tertiary": "#E9E9F1",
  "--ck-tertiary-border-radius": "22px",
  "--ck-tertiary-box-shadow":
    "inset 0 0 0 2px #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-body-action-color": "#79809C",
  "--ck-body-divider": "#D9DBE3",
  "--ck-body-color-danger": "#FF4E4E",
  "--ck-body-color-valid": "#32D74B",
  "--ck-body-disclaimer-background": "#F9FAFB",
  "--ck-body-disclaimer-font-size": "14px",
  "--ck-body-disclaimer-font-weight": "700",
  "--ck-body-disclaimer-color": "#959697",
  "--ck-body-disclaimer-link-color": "#646464",
  "--ck-body-disclaimer-link-hover-color": "#000000",
  "--ck-copytoclipboard-stroke": "#CCCCCC",
  "--ck-tooltip-background": "#ffffff",
  "--ck-tooltip-background-secondary": "#ffffff",
  "--ck-tooltip-color": "#999999",
  "--ck-tooltip-shadow": " 0 0 0 2px #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-spinner-color": "var(--ck-focus-color)",
  "--ck-dropdown-button-color": "#999999",
  "--ck-dropdown-button-box-shadow":
    "0 0 0 2px #DFE4EC,  0 2px 0 2px #DFE4EC, 0px 2px 4px rgba(0, 0, 0, 0.02)",
  "--ck-dropdown-button-background": "#fff",
  "--ck-dropdown-button-hover-color": "#8B8B8B",
  "--ck-dropdown-button-hover-background": "#F5F7F9",
  "--ck-dropdown-pending-color": "#848D9A",
  "--ck-dropdown-active-color": "#000000",
  "--ck-dropdown-active-static-color": "#848D9A",
  "--ck-dropdown-active-background": "#F5F7F9",
  "--ck-dropdown-color": "#848D9A",
  "--ck-dropdown-background": "#FFFFFF",
  "--ck-dropdown-box-shadow": "0px 2px 15px rgba(0, 0, 0, 0.15)",
  "--ck-dropdown-border-radius": "16px",
  "--ck-alert-color": "#848D9A",
  "--ck-alert-background": "#F5F7F9",
  "--ck-qr-border-radius": "24px",
  "--ck-qr-dot-color": "#111111",
  "--ck-qr-border-color": "#DFE4EC",
  "--ck-modal-h1-font-weight": "700",
  "--ck-modal-heading-font-weight": "700",
  "--ck-primary-button-font-weight": "700",
  "--ck-recent-badge-box-shadow": "inset 0 0 0 2px currentColor",
  "--ck-recent-badge-top-offset": "0px",
  "--ck-siwe-border": "#DFE4EC",
  "--ck-overlay-background": "#d5d7e1",
};
